server:
  port: 8020
spring:
  application:
    name: AllBuildingConsumer
  cloud:
    nacos:
      server-addr: localhost:8848
feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50